"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

setup(
    name="markdown-editor",
    setup_requires=['py2app'],
    app=['markdown-editor.py'],
    options=dict(py2app=dict(argv_emulation=True)),
)
